version: "3.9"
services:
  traffic-scanner:
    restart: always
    image: yuriyzabegaev/traffic-scanner:latest
    container_name: traffic-scanner
    volumes:
      - ${VOLUME_HOST_PATH}:/data:rw
    environment:
      - TIMEZONE=3
      - DATABASE_URL=sqlite:///data/db_test
      - TELEGRAM_BOT_TOKEN